---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.release }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Values.name }}-{{ .Values.release }}
      labels:
        app: {{ .Values.name }}
        tier: backend
        track: {{ .Values.track }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: hellocicd
        ports:
        - containerPort: 5000
        env:
        - name: RELEASE
          value: {{ .Values.release }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        workingDir: /src
