{{- if .Values.domain }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
  name: {{ .Values.name }}-internal-ingress
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.port }}
{{- end }}
